version: '3'

services:
  rootstalk-static:
    image: mcfatem/rootstalk:latest
    container_name: rootstalk-static
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.rootstalk-static-secure.entrypoints=https"
      - "traefik.http.routers.rootstalk-static-secure.rule=Host(`rootstalk-static.grinnell.edu`)"
      - "traefik.http.routers.rootstalk-static-secure.tls=true"
      - "traefik.http.routers.rootstalk-static-secure.tls.certresolver=http"
      - "traefik.http.routers.rootstalk-static-secure.service=rootstalk-static_rootstalk-static"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
